const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let current=JSON.parse(localStorage.getItem('activeScan')||'null'); let controls=null, stream=null, lastCode='', lastAt=0, photoData=null;
function toast(t){const e=$('#toast');e.textContent=t;e.style.display='block';setTimeout(()=>e.style.display='none',1800)}
function persist(){current?localStorage.setItem('activeScan',JSON.stringify(current)):localStorage.removeItem('activeScan'); updateHeader()}
function updateHeader(){$('#sessionLabel').textContent=current?`${current.name} • ${current.items.length} items`:'No active scan'}
function go(id){stopCamera(); $$('.screen').forEach(x=>x.classList.remove('active')); $('#'+id).classList.add('active'); if(id==='current')renderCurrent();if(id==='saved')renderSaved();}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
$('#startSession').onclick=()=>{const n=$('#scanName').value.trim()||`Scan ${new Date().toLocaleString()}`;current={id:Date.now(),name:n,created:new Date().toISOString(),items:[]};persist();go('scanner')};
async function startCamera(){stopCamera();$('#scanStatus').textContent='Starting rear camera…'; try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});$('#video').srcObject=stream;await $('#video').play();$('#scanStatus').textContent='Point barcode inside the box'; if('BarcodeDetector'in window){let detector=new BarcodeDetector({formats:['ean_13','ean_8','upc_a','upc_e','code_128','code_39','itf']});const tick=async()=>{if(!stream)return;try{let a=await detector.detect($('#video'));if(a[0])found(a[0].rawValue)}catch(e){}requestAnimationFrame(tick)};tick()}else if(window.ZXing){const reader=new ZXing.BrowserMultiFormatReader();controls=await reader.decodeFromVideoElement($('#video'),(result)=>{if(result)found(result.getText())})}else{$('#scanStatus').textContent='Scanner library unavailable. Manual barcode entry still works.'}}catch(e){$('#scanStatus').textContent='Camera could not start: '+e.message}}
function stopCamera(){try{controls&&controls.stop&&controls.stop()}catch(e){}controls=null;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}if($('#video'))$('#video').srcObject=null}
function found(code){const now=Date.now();if(code===lastCode&&now-lastAt<2500)return;lastCode=code;lastAt=now;stopCamera();loadItem(code)}
function loadItem(code){$('#itemBarcode').textContent=code;$('#itemPart').textContent='NOT FOUND';$('#itemDesc').textContent='Unmatched item';$('#itemSupplier').textContent='—';$('#qty').value=1;photoData=null;$('#photoPreview').hidden=true;go('item')}
$('#startCamera').onclick=startCamera;$('#stopCamera').onclick=stopCamera;$('#useManual').onclick=()=>{let c=$('#manualBarcode').value.trim();if(c)loadItem(c)};
$('#minus').onclick=()=>$('#qty').value=Math.max(1,(+$('#qty').value||1)-1);$('#plus').onclick=()=>$('#qty').value=(+$('#qty').value||1)+1;
$('#photo').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{photoData=r.result;$('#photoPreview').src=photoData;$('#photoPreview').hidden=false};r.readAsDataURL(f)};
$('#addItem').onclick=()=>{if(!current){toast('Start a scan first');go('newscan');return}const barcode=$('#itemBarcode').textContent,q=Math.max(1,+$('#qty').value||1);let existing=current.items.find(x=>x.barcode===barcode&&!photoData);if(existing)existing.qty+=q;else current.items.push({barcode,qty:q,part:'',description:'Unmatched item',supplier:'',photo:photoData,added:new Date().toISOString()});persist();toast('Added to scan');go('scanner')};
function renderCurrent(){const e=$('#currentList');if(!current){e.innerHTML='<div class="card">No active scan.</div>';return}e.innerHTML=current.items.length?'':'<div class="card">No items yet.</div>';current.items.forEach((x,i)=>{let d=document.createElement('div');d.className='row unmatched';d.innerHTML=`<b>${esc(x.barcode)}</b> <span class="badge">Qty ${x.qty}</span><br><span>${esc(x.description)}</span>${x.photo?'<br><span class="badge">Photo attached</span>':''}<button data-r="${i}">REMOVE</button>`;e.appendChild(d)});e.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{current.items.splice(+b.dataset.r,1);persist();renderCurrent()})}
$('#saveSession').onclick=()=>{if(!current)return toast('No active scan');let a=JSON.parse(localStorage.getItem('savedScans')||'[]');a=a.filter(x=>x.id!==current.id);a.unshift(current);localStorage.setItem('savedScans',JSON.stringify(a.slice(0,25)));toast('Scan saved');renderSaved()};
function renderSaved(){let a=JSON.parse(localStorage.getItem('savedScans')||'[]'),e=$('#savedList');e.innerHTML=a.length?'':'<div class="card">No saved scans yet.</div>';a.forEach((x,i)=>{let d=document.createElement('div');d.className='row';d.innerHTML=`<b>${esc(x.name)}</b><br>${x.items.length} items • ${new Date(x.created).toLocaleString()}<button data-o="${i}">OPEN</button>`;e.appendChild(d)});e.querySelectorAll('[data-o]').forEach(b=>b.onclick=()=>{current=a[+b.dataset.o];persist();go('current')})}
$('#partQuery').oninput=()=>{$('#searchResults').innerHTML=$('#partQuery').value?'<div class="card">Parts database not imported yet. This will search MechanicDesk + Our Data in the next build.</div>':''};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});updateHeader();
